/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package refatoradesktop;

import com.mysql.jdbc.Connection;
import java.awt.FileDialog;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author João
 */
public class Logado extends javax.swing.JFrame {

    /**
     * Creates new form Logado
     */
    
    MetodosOpera mo = new MetodosOpera();
    
    DefaultTableModel model;
    Connection con;
    
    public Logado() {
        System.err.println("Erro no login - Usuário não identificado");
    }
    
    public Logado(int codHotel)
    {
        initComponents();
        
        lblCod.setText(String.valueOf(codHotel));
        
        mo.conecta("143.106.241.3","cl17126","cl17126","cl*13022002");
               
        model = (DefaultTableModel) tblTabela.getModel();
        
        model.setColumnCount(6);
        model.setRowCount(0);
        tblTabela.getColumnModel().getColumn(0).setHeaderValue("IdUser");
        tblTabela.getColumnModel().getColumn(1).setHeaderValue("Numero Quarto");
        tblTabela.getColumnModel().getColumn(2).setHeaderValue("Check In");
        tblTabela.getColumnModel().getColumn(3).setHeaderValue("Check Out");
        tblTabela.getColumnModel().getColumn(4).setHeaderValue("Diária");
        tblTabela.getColumnModel().getColumn(5).setHeaderValue("Cobrança total");
        
        mo.PoeTabela(model,tblTabela,codHotel);
        
        
        txtNumero.setEnabled(false);
        txtUser.setEnabled(false);
        txtCin.setEnabled(false);
        txtCout.setEnabled(false);
        txtValtot.setEnabled(false);
        
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnSubmit.setVisible(false);
        btnFimRes.setVisible(false);
        btnConfirma.setVisible(false);
        btnCancelar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumero = new javax.swing.JTextField();
        txtValdia = new javax.swing.JTextField();
        txtValtot = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnImg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        txtCin = new javax.swing.JTextField();
        txtCout = new javax.swing.JTextField();
        btnFimRes = new javax.swing.JButton();
        lblCaminho = new javax.swing.JLabel();
        btnConfirma = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUser.setEnabled(false);

        jLabel1.setText("Numero");

        jLabel2.setText("Valor Diaria");

        jLabel3.setText("Valor Total");

        jLabel4.setText("Usuario");

        btnImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImgMouseClicked(evt);
            }
        });

        jLabel5.setText("Imagem");

        jLabel6.setText("Check-in");

        jLabel7.setText("Check-out");

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabela);

        btnNovo.setText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.setEnabled(false);
        btnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarMouseClicked(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        btnSubmit.setText("Cadastrar");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        jLabel8.setText("Seu Id:");

        btnFimRes.setText("Finalizar Reserva");
        btnFimRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFimResMouseClicked(evt);
            }
        });

        btnConfirma.setText("Confirmar Alterações");
        btnConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmaMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValdia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValtot, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(46, 46, 46)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnFimRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnImg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCod)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValtot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnFimRes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnApagar)
                                .addComponent(btnSubmit))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNovo)
                                .addComponent(btnEditar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(lblCod)
                                    .addComponent(btnConfirma)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCaminho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabelaMouseClicked
        // TODO add your handling code here:
        
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnSubmit.setVisible(false);
        
        int row = tblTabela.getSelectedRow();
        
        
        txtUser.setText(model.getValueAt(row,0).toString());
        txtNumero.setText(model.getValueAt(row,1).toString());
        
        if(model.getValueAt(row,2).toString()!= "")
        {
            txtCin.setText(model.getValueAt(row,2).toString());
            btnFimRes.setVisible(true);
        }
        else
        {
            txtCin.setText(model.getValueAt(row,2).toString());
            btnFimRes.setVisible(false);
        }
        
        if(model.getValueAt(row,3).toString()!= "")
        {
            txtCout.setText(model.getValueAt(row,3).toString());
            btnFimRes.setVisible(true);
        }
        else
        {
            txtCout.setText(model.getValueAt(row,3).toString());
            btnFimRes.setVisible(false);
        }
            
        
        txtValdia.setText(model.getValueAt(row,4).toString());
        txtValtot.setText(model.getValueAt(row,5).toString());
        
        mo.recuperaImg(txtNumero.getText(), lblCod.getText() , btnImg);
        
        txtNumero.setEnabled(false);
        txtUser.setEnabled(false);
        txtCin.setEnabled(false);
        txtCout.setEnabled(false);
        txtValtot.setEnabled(false);
        
    }//GEN-LAST:event_tblTabelaMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
        
        txtNumero.setEnabled(true);
        
        txtCin.setEnabled(false);
        txtCout.setEnabled(false);
        txtUser.setEnabled(false);
        
        //botoes
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnSubmit.setVisible(true);
        btnFimRes.setVisible(false);
        btnConfirma.setVisible(false);
        
        txtNumero.setText("");
        txtUser.setText("");
        txtCin.setText("");
        txtCout.setText("");
        txtValdia.setText("");
        txtValtot.setText("");
        
        btnImg.setIcon(null);
        lblCaminho.setText("");
        
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        try{
            if((txtNumero.getText().equals("")) || (txtValdia.getText().equals(""))  || (btnImg.getIcon()==null))
            {
                JOptionPane.showConfirmDialog(null,"Os campos Numero, Valor Diária e uma imagem são obrigatórios","Formulário Incompleto",JOptionPane.DEFAULT_OPTION);
            }
            else if(mo.verifyNumqto( Integer.parseInt( txtNumero.getText()), Integer.parseInt(lblCod.getText()) ) )
            {
                JOptionPane.showConfirmDialog(null,"Já existe um quarto com o número digitado","Número Repetido",JOptionPane.DEFAULT_OPTION);
            }
            else{
                mo.cadastraQuarto(txtNumero.getText(), txtValdia.getText() , lblCaminho.getText(),Integer.parseInt(lblCod.getText()) );
                System.out.println(lblCaminho.getText());
                mo.PoeTabela(model,tblTabela,Integer.parseInt(lblCod.getText()));

                btnSubmit.setVisible(false);
            }
        }catch(NumberFormatException ex)
        {
            JOptionPane.showConfirmDialog(null,"Digite apenas numeros","Erro de cadastro",JOptionPane.DEFAULT_OPTION);
        }
        
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImgMouseClicked
        // TODO add your handling code here:
        
        FileDialog fd = new FileDialog((Frame) null);
        fd.setVisible(true);
        System.out.println(fd.getDirectory()+fd.getFile()); // aqui esta o caminho
        lblCaminho.setText(fd.getDirectory()+fd.getFile());
        mo.carregaImg(btnImg,fd.getDirectory()+fd.getFile());
    }//GEN-LAST:event_btnImgMouseClicked

    private void btnApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarMouseClicked
        // TODO add your handling code here:
        
        int op = JOptionPane.showConfirmDialog(null,"Você tem certeza que quer excluir o Quarto?","Apagar",JOptionPane.YES_NO_OPTION);
        if(op == 0)
            mo.apagarQuarto(Integer.parseInt(txtNumero.getText()),Integer.parseInt(lblCod.getText()) );
        
        mo.PoeTabela(model,tblTabela,Integer.parseInt(lblCod.getText()));
        
        btnApagar.setEnabled(false);
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnApagarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:  
        txtNumero.setEnabled(false);
        
        txtCin.setEnabled(false);
        txtCout.setEnabled(false);
        txtUser.setEnabled(false);
        
        //botoes
        btnApagar.setEnabled(false);
        btnConfirma.setVisible(true);
        btnCancelar.setVisible(true);
        
        btnImg.setIcon(null);
        lblCaminho.setText("");
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnFimResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFimResMouseClicked
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null,"Você tem certeza que quer finalizar a reserva do cliente?","Finalizar",JOptionPane.YES_NO_OPTION);
        if(op == 0)
            mo.finalreserva(Integer.parseInt(txtNumero.getText()),Integer.parseInt(lblCod.getText()));
        
        mo.PoeTabela(model,tblTabela,Integer.parseInt(lblCod.getText()));
        btnFimRes.setVisible(false);
        txtCin.setText("");
        txtCout.setText("");
        txtUser.setText("");
    }//GEN-LAST:event_btnFimResMouseClicked

    private void btnConfirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmaMouseClicked
        // TODO add your handling code here:
        if((txtValdia.getText().equals("") ) || (txtValdia.getText() == null) || (btnImg.getIcon()==null))
            System.err.print("Calma lá, preencha todos os campos");
        else
            mo.editarQuarto(Float.parseFloat(txtValdia.getText()), Integer.parseInt(lblCod.getText()), Integer.parseInt(txtNumero.getText()), lblCaminho.getText());
             mo.PoeTabela(model,tblTabela,Integer.parseInt(lblCod.getText()));
            
            btnApagar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnImg.setIcon(null);
            btnConfirma.setVisible(false);
            btnCancelar.setVisible(false);
            lblCaminho.setText("");
    }//GEN-LAST:event_btnConfirmaMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        txtNumero.setEnabled(true);
        
        txtCin.setEnabled(false);
        txtCout.setEnabled(false);
        txtUser.setEnabled(false);
        
        //botoes
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnConfirma.setVisible(false);
        btnCancelar.setVisible(false);
        
        txtNumero.setText("");
        txtUser.setText("");
        txtCin.setText("");
        txtCout.setText("");
        txtValdia.setText("");
        txtValtot.setText("");
        
        btnImg.setIcon(null);
        lblCaminho.setText("");
        
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFimRes;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaminho;
    private javax.swing.JLabel lblCod;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtCin;
    private javax.swing.JTextField txtCout;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtValdia;
    private javax.swing.JTextField txtValtot;
    // End of variables declaration//GEN-END:variables
}
